### ISSUE TITLE
Ля ну и говно

### ISSUE THREAD

**Issue by SadPossum** [stillProger/testRep#1]
![image](https://user-images.githubusercontent.com/61198926/111911788-f6b91c80-8a77-11eb-910d-9fddd501e13f.png)

**Comment by stillProger** [comment]
ПОШЕЛ НАХУЙ

**Comment by SadPossum** [comment]
Сам иди

**Comment by stillProger** [comment]
АХАХАХАХ ДУРАК

**Comment by stillProger** [comment]
xzcxsdasdcascascasc
